using Err.ChangeTracking.SampleDemo.Models;

namespace Err.ChangeTracking.Tests;

public class AutoGenAttachedTrackerTests
{
    [Fact]
    public void AutoGen_AttachedTracker_Workflow()
    {
        // Arrange: Create a trackable model and initialize change tracking
        var model = new TestModel { Name = "m1" }.AsTrackable();
        
        // Verify the model implements IAttachedTracker (auto-generated by source generator)
        var attachedTracker = model as IAttachedTracker<TestModel>;
        var changeTracker = attachedTracker?.ChangeTracker;
        var defaultChangeTracker = model.GetChangeTracker();
        
        // Act: Modify the Name property (should be tracked)
        model.Name = "m1_test";
        
        // Assert: Verify the property was updated
        Assert.Equal("m1_test", model.Name);
        // Verify one change was recorded (Name: "m1" -> "m1_test")
        Assert.True( changeTracker?.IsDirty());
        Assert.True( changeTracker?.HasChanged(x => x.Name));
        
        // Verify we use attached tracker (inline property) rather than cache-based tracker
        // Attached tracker is faster as it stores the ChangeTracker directly on the instance
        Assert.NotNull(attachedTracker);
        Assert.NotNull(changeTracker);
        Assert.Equal(changeTracker, defaultChangeTracker);
    }
    
    
    [Fact]
    public void AutoGen_AttachedTracker_Innertyped_Workflow()
    {
        // Arrange: Create a trackable model and initialize change tracking
        var model = new OuterClass.InnerModel() { Value = 1}.AsTrackable();
        
        // Verify the model implements IAttachedTracker (auto-generated by source generator)
        var attachedTracker = model as IAttachedTracker<OuterClass.InnerModel>;
        var changeTracker = attachedTracker?.ChangeTracker;
        var defaultChangeTracker = model.GetChangeTracker();
        
        // Act: Modify the Name property (should be tracked)
        model.Value = 2;
        
        // Assert: Verify the property was updated
        Assert.Equal(2, model.Value);
        // Verify one change was recorded (Value: 1 -> 2)
        Assert.True( changeTracker?.IsDirty());
        Assert.True( changeTracker?.HasChanged(x => x.Value));
        
        // Verify we use attached tracker (inline property) rather than cache-based tracker
        // Attached tracker is faster as it stores the ChangeTracker directly on the instance
        Assert.NotNull(attachedTracker);
        Assert.NotNull(changeTracker);
        Assert.Equal(changeTracker, defaultChangeTracker);
    }
}