name: CD

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      public-release:
        description: 'Set Public Release'
        required: false
        default: 'false'
        type: boolean

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # This ensures a full clone instead of a shallow clone

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.x

      - name: Install Nerdbank.GitVersioning
        run: |
          dotnet tool install --global nbgv
          export PATH="$PATH:$HOME/.dotnet/tools"

      - name: Get version info
        run: nbgv get-version

      # Step 1: Build first
      - name: Build solution
        run: dotnet build --configuration Release -p:PublicRelease=${{ github.event.inputs.public-release}}

      # Step 2: Then pack
      - name: Pack projects
        run: dotnet pack --configuration Release --no-build --include-symbols -p:SymbolPackageFormat=snupkg -p:PublicRelease=${{ github.event.inputs.public-release}}

      # Push packages
      - name: Push NuGet packages
        run: |
          find . -name "*.nupkg" ! -name "*.symbols.nupkg" -exec dotnet nuget push {} \
            --api-key ${{ secrets.NUGET_API_KEY }} \
            --source https://api.nuget.org/v3/index.json \
            --skip-duplicate \;
          